$YELLOW_PROBABILITY = 0.0001;

//INFECTIONS
//probabilities
$TECH_PRIMITIVE_LV1_PROBABILITY=0.01;
$TECH_PRIMITIVE_LV2_PROBABILITY=0.01;
$TECH_MEDIUM_LV1_PROBABILITY=0.01;
$TECH_MEDIUM_LV2_PROBABILITY=0.01;
$TECH_HITECH_LV1_PROBABILITY=0.01;
$TECH_HITECH_LV2_PROBABILITY=0.01;

$TECH_TEMP_LV3_PROBABILITY=0.01;

$TEMP_COLD_LV1_PROBABILITY=0.01;
$TEMP_COLD_LV2_PROBABILITY=0.01;
$TEMP_TEMPERATE_LV1_PROBABILITY=0.01;
$TEMP_TEMPERATE_LV2_PROBABILITY=0.01;
$TEMP_HOT_LV1_PROBABILITY=0.01;
$TEMP_HOT_LV2_PROBABILITY=0.01;

$TEMP_DENS_LV3_PROBABILITY=0.01;

$DENS_LOW_LV1_PROBABILITY=0.01;
$DENS_LOW_LV2_PROBABILITY=0.01;
$DENS_MEDIUM_LV1_PROBABILITY=0.01;
$DENS_MEDIUM_LV2_PROBABILITY=0.01;
$DENS_HIGH_LV1_PROBABILITY=0.01;
$DENS_HIGH_LV2_PROBABILITY=0.01;

//costs
//costs = cost*(//already_upgraded)*COST_SCALING
$COST_SCALING=0.3;

$TECH_PRIMITIVE_LV1_COST=1;
$TECH_PRIMITIVE_LV2_COST=2;
$TECH_MEDIUM_LV1_COST=1;
$TECH_MEDIUM_LV2_COST=2;
$TECH_HITECH_LV1_COST=1;
$TECH_HITECH_LV2_COST=2;

$TECH_TEMP_LV3_COST=3;

$TEMP_COLD_LV1_COST=1;
$TEMP_COLD_LV2_COST=2;
$TEMP_TEMPERATE_LV1_COST=1;
$TEMP_TEMPERATE_LV2_COST=2;
$TEMP_HOT_LV1_COST=1;
$TEMP_HOT_LV2_COST=2;

$TEMP_DENS_LV3_COST=3;

$DENS_LOW_LV1_COST=1;
$DENS_LOW_LV2_COST=2;
$DENS_MEDIUM_LV1_COST=1;
$DENS_MEDIUM_LV2_COST=2;
$DENS_HIGH_LV1_COST=1;
$DENS_HIGH_LV2_COST=2;

//percentages
//to be added to disease.infection_percentage on upgrade
$TECH_PRIMITIVE_LV1_INFECTION_P=0.01;
$TECH_PRIMITIVE_LV2_INFECTION_P=0.01;
$TECH_MEDIUM_LV1_INFECTION_P=0.01;
$TECH_MEDIUM_LV2_INFECTION_P=0.01;
$TECH_HITECH_LV1_INFECTION_P=0.01;
$TECH_HITECH_LV2_INFECTION_P=0.01;

$TECH_TEMP_LV3_INFECTION_P=0.01;

$TEMP_COLD_LV1_INFECTION_P=0.01;
$TEMP_COLD_LV2_INFECTION_P=0.01;
$TEMP_TEMPERATE_LV1_INFECTION_P=0.01;
$TEMP_TEMPERATE_LV2_INFECTION_P=0.01;
$TEMP_HOT_LV1_INFECTION_P=0.01;
$TEMP_HOT_LV2_INFECTION_P=0.01;

$TEMP_DENS_LV3_INFECTION_P=0.01;

$DENS_LOW_LV1_INFECTION_P=0.01;
$DENS_LOW_LV2_INFECTION_P=0.01;
$DENS_MEDIUM_LV1_INFECTION_P=0.01;
$DENS_MEDIUM_LV2_INFECTION_P=0.01;
$DENS_HIGH_LV1_INFECTION_P=0.01;
$DENS_HIGH_LV2_INFECTION_P=0.01;

$INFECTED_ON_INFECTER_RATIO=0.01; //has to be lower -- 0.01

//enum temperature = {cold, temperate, hot}
//enum density = {low, medium, high}
//enum technologic_level = { primitive, medium ,hitech}



function gen(){
	return getRandomF(0,1);
}


